### PR TITLE
Add instructions to release on PyPI

### PR DESCRIPTION
**Pull request by fern4lvarez**

### CODE REVIEW

**Comment by TooAngel** [comment]
Hm, do we really need a script for:
python setup.py sdist upload

I'm not sure if you need the other parameters, so we could also add it to the README.md

**Comment by fern4lvarez** [comment]
Does that command also upload the targz file?

**Comment by fern4lvarez** [comment]
Updated commit and commit message.

**Comment by TooAngel** [comment]
If you change the title of the PR, I will merge it :-)

**Comment by fern4lvarez** [comment]
Done

**Pull request merged**
